dist: xenial
services:
  - xvfb
language: node_js
node_js:
  - '5'
addons:
  firefox: latest
sudo: false
install:
  - npm install
script:
  - set -e;
    npm run clean;
    npm run build;
    npm run test;
