language: node_js
node_js:
  - '5'
addons:
  firefox: latest
sudo: false
install:
  - npm install
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - set -e;
    npm run clean;
    npm run build;
    npm run test;
